from enum import Enum


class BusinessStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    CLOSED = "CLOSED"
    UNKNOWN = "UNKNOWN"


class VerificationStatus(str, Enum):
    UNVERIFIED = "UNVERIFIED"
    PARTIALLY_VERIFIED = "PARTIALLY_VERIFIED"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"


class LeadSource(str, Enum):
    MANUAL = "MANUAL"
    GOOGLE_MAPS = "GOOGLE_MAPS"
    DIRECTORY = "DIRECTORY"
    WEBSITE = "WEBSITE"
    REFERRAL = "REFERRAL"
    IMPORT = "IMPORT"
    OTHER = "OTHER"


class LeadStatus(str, Enum):
    NEW = "NEW"
    RESEARCHING = "RESEARCHING"
    QUALIFIED = "QUALIFIED"
    CONTACTED = "CONTACTED"
    REPLIED = "REPLIED"
    INTERESTED = "INTERESTED"
    FOLLOW_UP = "FOLLOW_UP"
    CONVERTED = "CONVERTED"
    NOT_INTERESTED = "NOT_INTERESTED"
    INVALID = "INVALID"
    LOST = "LOST"
    DO_NOT_CONTACT = "DO_NOT_CONTACT"


class PipelineStage(str, Enum):
    NEW = "NEW"
    RESEARCH = "RESEARCH"
    QUALIFIED = "QUALIFIED"
    PITCH_READY = "PITCH_READY"
    OUTREACH = "OUTREACH"
    CONVERSATION = "CONVERSATION"
    PROPOSAL = "PROPOSAL"
    NEGOTIATION = "NEGOTIATION"
    WON = "WON"
    LOST = "LOST"


class ServiceType(str, Enum):
    WEBSITE = "WEBSITE"
    WEBSITE_REDESIGN = "WEBSITE_REDESIGN"
    LANDING_PAGE = "LANDING_PAGE"
    ECOMMERCE = "ECOMMERCE"
    WEBSITE_OPTIMIZATION = "WEBSITE_OPTIMIZATION"
    MAINTENANCE = "MAINTENANCE"
    SEO = "SEO"
    UNKNOWN = "UNKNOWN"


class EvidenceType(str, Enum):
    NO_WEBSITE = "NO_WEBSITE"
    OUTDATED_WEBSITE = "OUTDATED_WEBSITE"
    MOBILE_PROBLEM = "MOBILE_PROBLEM"
    BROKEN_LINK = "BROKEN_LINK"
    SLOW_SITE = "SLOW_SITE"
    POOR_DESIGN = "POOR_DESIGN"
    MISSING_CONTACT = "MISSING_CONTACT"
    WEAK_CALL_TO_ACTION = "WEAK_CALL_TO_ACTION"
    SOCIAL_ONLY = "SOCIAL_ONLY"
    OTHER = "OTHER"


class IssueSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class OutreachChannel(str, Enum):
    EMAIL = "EMAIL"
    WHATSAPP = "WHATSAPP"
    MANUAL = "MANUAL"
    OTHER = "OTHER"


class OutreachDirection(str, Enum):
    OUTBOUND = "OUTBOUND"
    INBOUND = "INBOUND"


class OutreachMessageType(str, Enum):
    INITIAL_PITCH = "INITIAL_PITCH"
    FOLLOW_UP = "FOLLOW_UP"
    REPLY = "REPLY"
    INTRODUCTION = "INTRODUCTION"
    PROPOSAL = "PROPOSAL"
    OTHER = "OTHER"


class OutreachStatus(str, Enum):
    DRAFT = "DRAFT"
    READY = "READY"
    QUEUED = "QUEUED"
    SENT = "SENT"
    DELIVERED = "DELIVERED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ConversationStatus(str, Enum):
    OPEN = "OPEN"
    WAITING_FOR_REPLY = "WAITING_FOR_REPLY"
    REPLIED = "REPLIED"
    INTERESTED = "INTERESTED"
    FOLLOW_UP = "FOLLOW_UP"
    CLOSED = "CLOSED"
    DO_NOT_CONTACT = "DO_NOT_CONTACT"


class ConversationIntent(str, Enum):
    UNKNOWN = "UNKNOWN"
    INTERESTED = "INTERESTED"
    QUESTION = "QUESTION"
    PRICE_REQUEST = "PRICE_REQUEST"
    TIMELINE = "TIMELINE"
    NOT_INTERESTED = "NOT_INTERESTED"
    CALL_REQUEST = "CALL_REQUEST"
    MEETING_REQUEST = "MEETING_REQUEST"
    READY_TO_BUY = "READY_TO_BUY"
    OTHER = "OTHER"


class CampaignStatus(str, Enum):
    DRAFT = "DRAFT"
    READY = "READY"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class AgentType(str, Enum):
    LEAD_DISCOVERY = "LEAD_DISCOVERY"
    LEAD_VERIFICATION = "LEAD_VERIFICATION"
    BUSINESS_RESEARCH = "BUSINESS_RESEARCH"
    WEBSITE_AUDIT = "WEBSITE_AUDIT"
    LEAD_QUALIFICATION = "LEAD_QUALIFICATION"
    PITCH_GENERATION = "PITCH_GENERATION"
    CONVERSATION_ANALYSIS = "CONVERSATION_ANALYSIS"
    SALES_ORCHESTRATION = "SALES_ORCHESTRATION"


class AgentRunStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AIGenerationValidation(str, Enum):
    PENDING = "PENDING"
    VALID = "VALID"
    INVALID = "INVALID"
    REPAIRED = "REPAIRED"
